# This workflow runs when merging code to the main branch.
name: Merge Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        working-directory: .
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: nikosportolos/dart_package@v0.2.1
        with:
          coverage: true
          codecov: true
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
